#!/usr/bin/env bash

set -eu
set -o pipefail

routes="$(oc get routes -o json | jq -r '.items[].metadata.name')"

function add_hsts_annotation() {
    local route=$1
    local value=$2
    echo "annotate $route $value"
    oc annotate --overwrite route $route "haproxy.router.openshift.io/hsts_header"="$value"
}

for route in $routes; do
    host="$(oc get routes $route -o json | jq -r '.spec.host')"
    echo "route=$route, host=$host"

    oc annotate --overwrite route $route "haproxy.router.openshift.io/hsts_header"="max-age=99999"
    sleep 10
    curl -i -s -k -L http://"$host" | grep "strict-transport-security: max-age=99999"

    oc annotate --overwrite route $route "haproxy.router.openshift.io/hsts_header"="max-age=99998;preload"
    sleep 10
    curl -i -s -k -L http://"$host" | grep "strict-transport-security: max-age=99998;preload"

    oc annotate --overwrite route $route "haproxy.router.openshift.io/hsts_header"="max-age=99997;preload;includesubdomains"
    sleep 10
    curl -i -s -k -L http://"$host" | grep "strict-transport-security: max-age=99997;preload;includesubdomains"

    oc annotate --overwrite route $route "haproxy.router.openshift.io/hsts_header"="max-age=10000"
    sleep 10
    curl -i -s -k -L http://"$host" | grep "strict-transport-security: max-age=10000"
done
