#!/bin/bash

TOPDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"

old_pids=$(pidof haproxy)
echo "$(date) -- oldpids: $old_pids"

set -eu
set -o nounset

mkdir -p /var/tmp/haproxy/run
[ -S /var/tmp/haproxy/run/haproxy.sock ] || mkfifo /var/tmp/haproxy/run/haproxy.sock

config_file=$TOPDIR/haproxy.cfg
#echo "config file: $config_file"

pid_file=/var/tmp/haproxy/run/haproxy.pid

[ -s $config_file ] || mkfifo $config_file

haproxy_binary=~/haproxy-2.0/haproxy
haproxy_binary=~/haproxy-1.8/haproxy

reload_status=0
if [ -n "$old_pids" ]; then
  #LD_PRELOAD=$TOPDIR/liballoc.so ~/haproxy-1.8/haproxy -f $config_file -p $pid_file -x /var/tmp/haproxy/run/haproxy.sock -sf $old_pids
  $haproxy_binary -f $config_file -p $pid_file -x /var/tmp/haproxy/run/haproxy.sock -sf $old_pids
  reload_status=$?
else
  #LD_PRELOAD=$TOPDIR/liballoc.so ~/haproxy-1.8/haproxy -f $config_file -p $pid_file
  $haproxy_binary -f $config_file -p $pid_file
  reload_status=$?
fi

[ $reload_status -ne 0 ] && exit $reload_status
