kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: dnstest
parameters:
- name: IMAGE
  value: quay.io/amcdermo/thanos-dnstest@sha256:fe0452aa25e0ceba73c7d40dea7f6144f46d354a67b96a6bd7a091ad8b639996
  required: true
- name: NAME
  value: "_grpc._tcp.prometheus-operated.openshift-monitoring.svc.cluster.local"
  required: true
- name: DEBUG
  value: ""                     # optionally "-debug"
- name: INTERVAL
  value: "6"
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: dnstest
    labels:
      app: dnstest
  spec:
    containers:
    - name: thanos-miekgdns
      command: [ "/usr/local/bin/thanos-nslookup" ]
      args:
        - --address
        - ${NAME}
        - --resolver.name
        - miekgdns
      image: ${IMAGE}
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
    - name: thanos-golang
      command: [ "/usr/local/bin/thanos-nslookup" ]
      args:
        - --address
        - ${NAME}
        - --resolver.name
        - golang
      image: ${IMAGE}
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
    - name: golang-nslookup-cgo-enabled
      command: [ "/usr/local/bin/golang-nslookup-cgo-enabled" ]
      args:
        - --address
        - ${NAME}
        - --resolver.name
        - golang-nslookup-cgo-enabled
      image: ${IMAGE}
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
    - name: golang-nslookup-cgo-disabled
      command: [ "/usr/local/bin/golang-nslookup-cgo-disabled" ]
      args:
        - --address
        - ${NAME}
        - --resolver.name
        - golang-nslookup-cgo-disabled
      image: ${IMAGE}
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
    - name: nslookup
      image: quay.io/openshift/origin-hello-openshift
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - -c
      args:
        - trap 'kill -TERM $child' TERM; while :; do nslookup ${DEBUG} ${NAME}; echo "nslookup status $?"; sleep ${INTERVAL}; done | cat -n & child=$!; wait $child
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 0s
