apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ingress-scale-on-pod-selector
spec:
  scaleTargetRef:
    apiVersion: operator.openshift.io/v1
    kind: IngressController
    name: default
    envSourceContainerName: ingress-operator
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 1
  cooldownPeriod:  1            # seconds
  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      namespace: openshift-ingress-operator
      metricName: 'ingress_controller_nodes_active'
      threshold: '1'
      query: 'sum(ingress_controller_nodes_active)'
      authModes: "bearer"
    authenticationRef:
      name: keda-trigger-auth-prometheus
