apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: bz1829779-hostnetwork
    name: bz1829779-hostnetwork
    namespace: default
  spec:
    replicas: 2
    selector:
      app: bz1829779-hostnetwork
    template:
      metadata:
        labels:
          app: bz1829779-hostnetwork
      spec:
        containers:
        - image: frobware/bz1829779-server@sha256:bb27caa9dc63d307fec7a018e1721042136566d05a61db440af4cf53a102e314
          imagePullpolicy: IfNotPresent
          name: server
          command: ["/workdir/server"]
        hostNetwork: true
        nodeSelector:
          role: node
          router: enabled
        securityContext: {}
        restartPolicy: Always
        serviceAccount: router
        serviceAccountName: router
        clusterIP: None
        dnsPolicy: ClusterFirstWithHostNet
    ports:
    - name: 3264-tcp
      protocol: TCP
      containerPort: 3264
    selector:
      matchLabels:
        app: bz1829779-hostnetwork
