apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: coredns-a
    labels:
      app: coredns-a
  spec:
    selector:
      app: coredns-a
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: dns
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: coredns-a
  spec:
    replicas: 1
    template:
      metadata:
        name: coredns-a
        labels:
          app: coredns-a
      spec:
        containers:
        - image: quay.io/submariner/nettest
          name: netshoot
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10; done"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - image: amouat/network-utils
          name: nslookup-fedoraproject
          command: ["/bin/sh"]
          args: ["-c", "while :; do date; for i in $(seq 1 100); do nslookup -port=5353 fedoraproject.org $MY_POD_IP; done; sleep 5; done"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - image: amouat/network-utils
          name: nslookup-github
          command: ["/bin/sh"]
          args: ["-c", "while :; do date; for i in $(seq 1 100); do nslookup -port=5353 www.github.com $MY_POD_IP; done; sleep 5; done"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - image: amouat/network-utils
          name: nslookup-google
          command: ["/bin/sh"]
          args: ["-c", "while :; do date; for i in $(seq 1 100); do nslookup -port=5353 www.google.nl $MY_POD_IP; done; sleep 5; done"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - image: amouat/network-utils
          name: nslookup-local
          command: ["/bin/sh"]
          args: ["-c", "while :; do date; for i in $(seq 1 100); do nslookup -port=1234 www.google.nl 192.168.7.64; done; sleep 5; done"]
        - image: amouat/network-utils
          name: nslookup-shell
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10; done"]
        - image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:aaf0854244f356ccb3f1cd70356362ac5ef7a9f227e08128740306430fd75497
#1.6.6. - image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:790915e54be36106bd8e7700780cee399be71569f83d6aee6747c6a0131eb749
          name: coredns
          command: ["/bin/sh"]
          args: ["-c", "sleep 5; a=$(dig +short coredns-b.coredns-test.svc.cluster.local); echo $a; cp /etc/coredns/Corefile /tmp; sed -i \"s/XXXX/$a/\" /tmp/Corefile; /usr/bin/coredns -conf /tmp/Corefile"]
          ports:
          - containerPort: 5353
            name: dns
            protocol: UDP
          - containerPort: 5353
            name: dns-tcp
            protocol: TCP
          volumeMounts:
          - name: corefile
            mountPath: /etc/coredns
        volumes:
        - name: corefile
          configMap:
            name: coredns-a
      imagePullPolicy: IfNotPresent
    selector:
      matchLabels:
        app: coredns-a
- apiVersion: v1
  kind: ConfigMap
  labels:
    app: coredns-a
  metadata:
    name: coredns-a
  data:
    Corefile: |
      .:5353 {
        log
        bufsize 512
        errors
        ready
        forward . XXXX:5353 {
            policy sequential
        }
        cache 3 {
            denial 9984 3
        }
        reload
      }
