apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: coredns-b
    labels:
      app: coredns-b
  spec:
    selector:
      app: coredns-b
    ports:
    - name: dns
      port: 5353
      protocol: UDP
      targetPort: 5353
    - name: dns-tcp
      port: 5353
      protocol: TCP
      targetPort: 5353
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: coredns-b
  spec:
    replicas: 1
    template:
      metadata:
        name: coredns-b
        labels:
          app: coredns-b
      spec:
        containers:
        - image: nicolaka/netshoot
          name: netshoot
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10; done"]
        - image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:aaf0854244f356ccb3f1cd70356362ac5ef7a9f227e08128740306430fd75497
          name: coredns
          command: ["/usr/bin/coredns"]
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
          - containerPort: 5353
            name: dns
            protocol: UDP
          - containerPort: 5353
            name: dns-tcp
            protocol: TCP
          volumeMounts:
          - name: corefile
            mountPath: /etc/coredns
        volumes:
        - name: corefile
          configMap:
            name: coredns-b
      imagePullPolicy: IfNotPresent
    selector:
      matchLabels:
        app: coredns-b
- apiVersion: v1
  kind: ConfigMap
  labels:
    app: coredns-b
  metadata:
    name: coredns-b
  data:
    Corefile: |
      .:5353 {
        log
        bufsize 512
        errors
        health {
            lameduck 3s
        }
        ready
        forward . 1.1.1.1 {
            policy sequential
        }
        cache 3
        reload
      }
