apiVersion: v1
kind: List
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: shard1
    namespace: openshift-ingress-operator
  spec:
    domain: shard1.apps.amcdermo-2021-01-15-0830.gcp.devcluster.openshift.com
    endpointPublishingStrategy:
      type: LoadBalancerService
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
    routeSelector:
      matchLabels:
        type: shard1
  status: {}
