FROM golang:1.18 as builder

ENV GOOS=linux
ENV GOARCH=amd64
WORKDIR /workspace

COPY Makefile Makefile
COPY go.mod go.mod
COPY go.sum go.sum

COPY pkg/ pkg/
COPY main.go main.go

RUN go build -o node-ready-app
RUN ls -trl

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
WORKDIR /
COPY --from=builder /workspace/node-ready-app .
# 65532 is numeric for nonroot
USER 65532:65532

ENTRYPOINT ["/node-ready-app"]
