FROM golang:1.18 as builder
WORKDIR /workspace
COPY . .
RUN make build
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
WORKDIR /
COPY --from=builder /workspace/nodes-ready-app .
# 65532 is numeric for nonroot
USER 65532:65532
ENTRYPOINT ["/nodes-ready-app"]
