apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodes-ready-app
  name: nodes-ready-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodes-ready-app
  template:
    metadata:
      labels:
        app: nodes-ready-app
    spec:
      containers:
      - name: nodes-ready-app
        image: quay.io/amcdermo/nodes-ready-app:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: UPDATE_INTERVAL
            value: "5s"
      serviceAccountName: ingress-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodes-ready-app
  annotations:
    prometheus.io/scrape: "true"
  name: nodes-ready-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    type: keda-testing
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: keda-nodes-ready-app-sm
spec:
  endpoints:
  - scheme: http
    port: http
  namespaceSelector: {}
  selector:
    matchLabels:
       app: nodes-ready-app
