#!/usr/bin/bash

set -eu
set -o pipefail

: ${DATAFILE:=results/${N:-1000}/joblog.dat}

echo "Analyzing ${DATAFILE}"

echo "curl requests that exceeded the timeout:"
sqlite3 <<EOF | awk '{ print "  ", $0 }' | cat -n
.separator "\t"
.import $DATAFILE results
.headers on
select Seq,Starttime,JobRuntime,Receive,Exitval from results where Exitval != 0 and Receive == 0;
EOF

echo
echo "curl requests that didn't complete:"
sqlite3 <<EOF | awk '{ print "  ", $0 }' | cat -n
.separator "\t"
.import $DATAFILE results
.headers on
select Seq,Starttime,JobRuntime,Receive,Exitval from results where Exitval != 0 and Receive != 0;
EOF

echo
echo "count(curl requests that exceeded the timeout):"
sqlite3 <<EOF
.separator "\t"
.import $DATAFILE results
select count(*) from results where Exitval != 0 and Receive == 0;
EOF

echo
echo "count(curl requests that didn't complete):"
sqlite3 <<EOF
.separator "\t"
.import $DATAFILE results
select count(*) from results where Exitval != 0 and Receive != 0;
EOF

echo
echo "count(failed requests): "
sqlite3 <<EOF
.separator "\t"
.import $DATAFILE results
select count(*) from results where Exitval != 0;
EOF

echo
echo "count(successful requests): "
sqlite3 <<EOF
.separator "\t"
.import $DATAFILE results
select count(*) from results where Exitval == 0;
EOF
