#!/usr/bin/bash

set -eu

: "${RESULTSDIR:=results}"
: "${N:=1000}"

: ${HOST:=$(oc get routes bz1841454-edge -o json | jq -r '.spec.host')}

host="$HOST"
date="$(date +%Y-%m-%d-%H%M%S | sed -e 's/ /-/g' -e 's/:/-/g')"
jobdir="${RESULTSDIR}/${date}---${N}"

rm -rf "$jobdir"
mkdir -p "$jobdir"

for i in $(seq 1 $N); do
    echo "curl -i -v --trace-time --trace-ascii ${jobdir}/curl-output-$i.trace --output ${jobdir}/curl-output-$i.stdout -k -m ${TIMEOUT:-10} ${CURLARGS:-} -X POST -H 'Content-Type:application/json' --data @${POSTDATA:-images-small.json} https://$host 2> ${jobdir}/curl-output-$i.stderr" >> "${jobdir}/jobs"
done

parallel --eta --bar --keep-order --joblog "${jobdir}/joblog.dat" --jobs "${P:-200}" < "${jobdir}/jobs" > /dev/null || true
./analyze-results "$jobdir" | tee "$jobdir/results.txt"
