#!/bin/sh

mkdir -p /var/tmp/haproxy && \
    mkdir -p /var/tmp/haproxy/run && \
    mkdir -p /var/tmp/haproxy/router/{certs,cacerts,whitelists} && \
    mkdir -p /var/tmp/haproxy/{conf/.tmp,run,bin,log} && \
    touch /var/tmp/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config}
