apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: TLS_CACRT
- name: TLS_CRT
- name: TLS_KEY
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: destca-default-cert-reencrypt
  spec:
    port:
      targetPort: 8443
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
      key: |-
        ${TLS_KEY}
      certificate: |-
        ${TLS_CRT}
      caCertificate: |-
        ${TLS_CACRT}
    to:
      kind: Service
      name: destca
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: destca-edge
  spec:
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: destca
      weight: 100
    wildcardPolicy: None
