---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert-destca
  name: destca
  labels:
    app: destca
spec:
  selector:
    app: destca
  ports:
  - port: 8080
    name: http-8080
    protocol: TCP
    targetPort: 8080
  - port: 8443
    name: https-8443
    protocol: TCP
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: destca
spec:
  selector:
    matchLabels:
      app: destca
  template:
    metadata:
      labels:
        app: destca
    spec:
      containers:
      - name: server
        image: quay.io/openshift/origin-cluster-ingress-operator:4.9.0
        command: ["ingress-operator", "serve-http2-test-server"]
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: cert
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 30
          successThreshold: 1
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 30
          successThreshold: 1
      volumes:
      - name: cert
        secret:
          secretName: serving-cert-destca
