#!/usr/bin/env bash

set -eu

domain=$(oc get -n openshift-ingress-operator ingresscontroller/default -o yaml | yq .status.domain)

TLS_KEY="$(cat /home/aim/.acme.sh/*.${domain}/*.${domain}.key)"
TLS_CRT="$(cat /home/aim/.acme.sh/*.${domain}/*.${domain}.cer)"
TLS_CACRT="$(cat /home/aim/.acme.sh/*.${domain}/ca.cer)"

# Find the first router pod in the openshift-ingress namespace.
pod=$(oc get pods -n openshift-ingress -l ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default -o jsonpath='{.items[0].metadata.name}')

if [[ -z "$pod" ]]; then
    echo "No router pod found in the openshift-ingress namespace."
    exit 1
fi

DEST_CACRT="$(oc exec -n openshift-ingress -c router "$pod" -- cat /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt)"

oc delete --all routes
oc delete --all services
oc delete --all deployments

pushd server

make
CGO_ENABLED=0 go build html-server.go
podman build -t html-server .
podman tag localhost/html-server:latest registry.int.frobware.com/destca/html-server
podman push registry.int.frobware.com/destca/html-server

oc process TLS_KEY="$TLS_KEY" TLS_CRT="$TLS_CRT" TLS_CACRT="$TLS_CACRT" -f ./routes.yaml -o yaml | oc apply -f -

oc apply -f deployment.yaml
oc apply -f service.yaml

popd

oc process DEST_CACRT="$DEST_CACRT" TLS_KEY="$TLS_KEY" TLS_CRT="$TLS_CRT" TLS_CACRT="$TLS_CACRT" -f ./destca-routes.yaml -o yaml | oc apply -f -
oc apply -f destca-service.yaml
oc apply -f destca-deployment.yaml
oc get all
