#!/usr/bin/env bash

set -eu

domain=$(oc get -n openshift-ingress-operator ingresscontroller/default -o yaml | yq .status.domain)

tls_key="$(cat /home/aim/.acme.sh/*.${domain}/*.${domain}.key)"
tls_crt="$(cat /home/aim/.acme.sh/*.${domain}/*.${domain}.cer)"
tls_cacrt="$(cat /home/aim/.acme.sh/*.${domain}/ca.cer)"

# Find the first router pod in the openshift-ingress namespace.
pod=$(oc get pods -n openshift-ingress -l ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default -o jsonpath='{.items[0].metadata.name}')

if [[ -z "$pod" ]]; then
    echo "No router pod found in the openshift-ingress namespace."
    exit 1
fi

dest_cacrt="$(oc exec -n openshift-ingress -c router "$pod" -- cat /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt)"

oc delete --all routes
oc delete --all services
oc delete --all deployments

pushd server
make
CGO_ENABLED=0 go build html-server.go
podman build -t html-server .
podman tag localhost/html-server:latest registry.int.frobware.com/destca/html-server
podman push registry.int.frobware.com/destca/html-server
popd

pushd browser-test
oc apply -f deployment.yaml
oc apply -f service.yaml
oc process TLS_KEY="$tls_key" TLS_CRT="$tls_crt" TLS_CACRT="$tls_cacrt" -f ./routes.yaml -o yaml | oc delete --ignore-not-found -f -
oc process TLS_KEY="$tls_key" TLS_CRT="$tls_crt" TLS_CACRT="$tls_cacrt" -f ./routes.yaml -o yaml | oc apply -f -
popd

pushd destca-test
oc apply -f service.yaml
oc apply -f deployment.yaml
./process-routes.sh ../certs/catpictures-destca.apps.ocp414.int.frobware.com catpictures-route.yaml
./process-routes.sh ../certs/payroll-destca.apps.ocp414.int.frobware.com payroll-route.yaml
popd

#oc get all
