---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ocpbugs-173-server
  labels:
    app: ocpbugs-173-server
  name: ocpbugs-173-server
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ocpbugs-173-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ocpbugs-173-server
  name: ocpbugs-173-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocpbugs-173-server
  template:
    metadata:
      labels:
        app: ocpbugs-173-server
    spec:
      containers:
      - name: ocpbugs-173-server
        image: quay.io/amcdermo/ocpbugs-173-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: cert
      volumes:
      - name: cert
        secret:
          secretName: ocpbugs-173-server
