#!/bin/bash

TOPDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"
config_file=$TOPDIR/haproxy.cfg

haproxy_binary=/home/aim/src/github.com/frobware/haproxy-1.8/build/bin/haproxy
haproxy_binary=/home/aim/src/github.com/frobware/haproxy-2.2/build/bin/haproxy

set -o nounset

pid_file=/var/tmp/haproxy/run/haproxy.pid
old_pids=$(pidof haproxy)

$haproxy_binary -v
reload_status=0
if [ -n "$old_pids" ]; then
    $haproxy_binary -f $config_file -p $pid_file -x /var/tmp/haproxy/run/haproxy.sock -sf $old_pids
    reload_status=$?
else
    $haproxy_binary -f $config_file -p $pid_file
    reload_status=$?
fi

[ $reload_status -ne 0 ] && exit $reload_status
