apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocpbugs40850-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocpbugs40850-test
  template:
    metadata:
      labels:
        app: ocpbugs40850-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ocpbugs40850-test
        image: quay.io/amcdermo/ocpbugs40850-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        ports:
        - containerPort: 8080
          protocol: TCP
          name: "http"
        - containerPort: 8443
          protocol: TCP
          name: "https"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: cert
      volumes:
      - name: cert
        secret:
          secretName: serving-cert-ocpbugs40850-test
