apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocpbugs40850-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocpbugs40850-test
  template:
    metadata:
      labels:
        app: ocpbugs40850-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ocpbugs40850-test
        image: quay.io/amcdermo/ocpbugs40850-server:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: HEALTH_PORT
          value: "1050"
        - name: SINGLE_TE_PORT
          value: "1030"
        - name: DUPLICATE_TE_PORT
          value: "1040"
        - name: SINGLE_TE_TLS_PORT
          value: "1060"
        - name: DUPLICATE_TE_TLS_PORT
          value: "1070"
        ports:
        - containerPort: 1030
          protocol: TCP
          name: "single-te"
        - containerPort: 1040
          protocol: TCP
          name: "dup-te"
        - containerPort: 1050
          protocol: TCP
          name: "health"
        - containerPort: 1060
          protocol: TCP
          name: "single-te-tls"
        - containerPort: 1070
          protocol: TCP
          name: "dup-te-tls"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1050
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1050
          initialDelaySeconds: 1
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: cert
      volumes:
      - name: cert
        secret:
          secretName: serving-cert-ocpbugs40850-test
