apiVersion: v1
kind: Service
metadata:
  name: ocpbugs40850-test
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert-ocpbugs40850-test
spec:
  selector:
    app: ocpbugs40850-test
  ports:
  - name: single-te
    protocol: TCP
    port: 1030
    targetPort: 1030
  - name: dup-te
    protocol: TCP
    port: 1040
    targetPort: 1040
  - name: health-port
    protocol: TCP
    port: 1050
    targetPort: 1050
  - name: single-te-tls
    protocol: TCP
    port: 1060
    targetPort: 1060
  - name: dup-te-tls
    protocol: TCP
    port: 1070
    targetPort: 1070
