#!/usr/bin/env bash

if ! type -P sqlite3 >/dev/null 2>&1; then
    echo "sqlite3 missing; yum install -y /usr/bin/sqlite3"
    exit 1
fi

set -u
set -o pipefail

host=${1:?no hostname specified}
results_file=$(mktemp)

for i in $(seq 1 ${N:-5000}); do
    curl -4 -o /dev/null -k -L -s -w "${i} ns %{time_namelookup} connect %{time_connect} pre %{time_pretransfer} start %{time_starttransfer} status %{http_code} port %{local_port} total %{time_total}\n" "$host";
done | tee $results_file
