#!/usr/bin/env bash

if ! type -P sqlite3 >/dev/null 2>&1; then
    echo "missing sqlite3 dependency; yum install -y /usr/bin/sqlite3"
    exit 1
fi

if ! type -P tshark >/dev/null 2>&1; then
    echo "missing tshark dependency; yum install -y /usr/bin/tshark"
    exit 1
fi

set -eu
set -o pipefail

pcap_file=${1:?no pcap file specified}
tmpfile=$(mktemp)
thisdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

tshark -r ${pcap_file} -Y "http.time" | awk '{printf "%.3f\n", $12}' > $tmpfile

"$thisdir/curler/sqlite3" <<EOF
.separator " "
.headers on
.mode column
CREATE TABLE results (time_total REAL);
.import $tmpfile results

SELECT CAST(Min(time_total) * 1000 AS INTEGER) AS "MIN",
       CAST(Max(time_total) * 1000 AS INTEGER) AS "MAX",
       CAST(Avg(time_total) * 1000 AS INTEGER) AS "AVG"
FROM   results;

SELECT CAST(histo.bin * 1000 AS INTEGER) as "bin(ms)",
       histo.bincount,
       histo.accumcount,
       Cast(Sum(bincount)
	      OVER (
		ORDER BY accumcount) / Cast((SELECT Count(time_total)
					     FROM   results) AS REAL) * 100.0 AS
	    INTEGER)        AS "acccum%age"
FROM   Histo("results", "time_total", ${NBINS:-30}, (SELECT Min(time_total)
						FROM results) - 0.0001,
					     (SELECT Max(time_total)
						FROM results) + 0.0001);
EOF

rm -f $tmpfile
