apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: bz1829779
  spec:
    selector:
      app: bz1829779
    ports:
      - port: 8080
        name: http
        targetPort: 8080
        protocol: TCP
- apiVersion: v1
  kind: ConfigMap
  labels:
    app: bz1829779
  metadata:
    name: src-config
  data:
    go.mod: |
        module bz1829779
        go 1.14
        require github.com/fatih/color v1.9.0
    go.sum: |
        github.com/fatih/color v1.9.0 h1:8xPHl4/q1VyqGIPif1F+1V3Y3lSmrq01EabUW3CoW5s=
        github.com/fatih/color v1.9.0/go.mod h1:eQcE1qtQxscV5RaZvpXrrb8Drkc3/DdQ+uUYCNjL+zU=
        github.com/mattn/go-colorable v0.1.4 h1:snbPLB8fVfU9iwbbo30TPtbLRzwWu6aJS6Xh4eaaviA=
        github.com/mattn/go-colorable v0.1.4/go.mod h1:U0ppj6V5qS13XJ6of8GYAs25YV2eR4EVcfRqFIhoBtE=
        github.com/mattn/go-isatty v0.0.8/go.mod h1:Iq45c/XA43vh69/j3iqttzPXn0bhXyGjM0Hdxcsrc5s=
        github.com/mattn/go-isatty v0.0.11 h1:FxPOTFNqGkuDUGi3H/qkUbQO4ZiBa2brKq5r0l8TGeM=
        github.com/mattn/go-isatty v0.0.11/go.mod h1:PhnuNfih5lzO57/f3n+odYbM4JtupLOxQOAqxQCu2WE=
        golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
        golang.org/x/sys v0.0.0-20191026070338-33540a1f6037 h1:YyJpGZS1sBuBCzLAR1VEpK193GlqGZbnPFnPV/5Rsb4=
        golang.org/x/sys v0.0.0-20191026070338-33540a1f6037/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
    server.go: |
        package main
        import (
        	"encoding/json"
        	"fmt"
        	"io/ioutil"
        	"log"
        	"math/rand"
        	"net/http"
        	"net/url"
        	"os"
        	"sync/atomic"
        	"time"
        )
        const (
        	defaultHTTPPort = "8080"
        )
        func lookupEnv(key, defaultVal string) string {
        	if val, ok := os.LookupEnv(key); ok {
        		return val
        	}
        	return defaultVal
        }
        type RequestSummary struct {
        	URL     string
        	Method  string
        	Headers http.Header
        	Params  url.Values
        	Auth    *url.Userinfo
        	Body    string
        }
        var clientCon int64 = 0
        var randomSrc = rand.NewSource(time.Now().Unix())
        func init() {
        	log.SetFlags(log.LstdFlags | log.Lmicroseconds)
        }
        func main() {
        	busyTime, err := time.ParseDuration(lookupEnv("BUSY_TIMEOUT", "0s"))
        	if err != nil {
        		log.Fatalf("failed to parse BUSY_TIMEOUT: %v", err)
        	}
        	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        		now := time.Now()
        		atomic.AddInt64(&clientCon, 1)
        		n := clientCon
        		// log.Println("connection", n, r.RemoteAddr)
        		bytes, err := ioutil.ReadAll(r.Body)
        		if err != nil {
        			http.Error(w, err.Error(), http.StatusInternalServerError)
        			return
        		}
        		rs := RequestSummary{
        			URL:     r.URL.RequestURI(),
        			Method:  r.Method,
        			Headers: r.Header,
        			Params:  r.URL.Query(),
        			Auth:    r.URL.User,
        			Body:    string(bytes),
        		}
        		resp, err := json.MarshalIndent(&rs, "", "\t")
        		if err != nil {
        			http.Error(w, err.Error(), http.StatusInternalServerError)
        			return
        		}
        		if busyTime != 0 {
        			time.Sleep(busyTime)
        		}
        		w.Write(resp)
        		w.Write([]byte("\n"))
        		d := time.Now().Sub(now)
        		if d > 1*time.Second {
        			log.Println("c-complete", n, r.RemoteAddr, busyTime, time.Now().Sub(now))
        		}
        	})
        	http.HandleFunc("/healthz", func(w http.ResponseWriter, req *http.Request) {
        		fmt.Fprint(w, "ready")
        	})
        	port := lookupEnv("HTTP_PORT", defaultHTTPPort)
        	log.Printf("Listening on port %v\n", port)
        	if err := http.ListenAndServe(":"+port, nil); err != nil {
        		log.Fatal(err)
        	}
        }
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: bz1829779
    labels:
      app: bz1829779
  spec:
    replicas: 2
    template:
      metadata:
        name: bz1829779
        labels:
          app: bz1829779
      spec:
        containers:
        - image: golang:1.14
          name: server
          command: ["go", "run", "/go/src/server.go"]
          env:
          - name: BUSY_TIMEOUT
            value: "0"
          - name: GO111MODULE
            value: "auto"
          - name: GOCACHE
            value: "/tmp"
          volumeMounts:
          - name: src-volume
            mountPath: /go/src
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
        volumes:
        - name: src-volume
          configMap:
            name: src-config
    selector:
      matchLabels:
        app: bz1829779
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: bz1829779
    name: bz1829779-edge
  spec:
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      key: |-
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIAW+ecg2cZR47ItbI898N3nJduh9UJNv+b0cOwH/Z1BEoAoGCCqGSM49
        AwEHoUQDQgAEx0/5sEgiUPFdcbd4dSllkul8s68RQ5WxIjfwWYMdfYLiLLqP1lkz
        4UYpwAW/t63qBx3jRhPgkUxh5saJP9Qu5Q==
        -----END EC PRIVATE KEY-----
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIBgTCCASagAwIBAgIRALutWdExjxX8fWljW+lcYbswCgYIKoZIzj0EAwIwJDEQ
        MA4GA1UEChMHUmVkIEhhdDEQMA4GA1UEAxMHUm9vdCBDQTAgFw0yMDA1MTExMDU2
        NThaGA8yMTIwMDQxNzEwNTY1OFowJjEQMA4GA1UEChMHUmVkIEhhdDESMBAGA1UE
        AwwJdGVzdF9jZXJ0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEx0/5sEgiUPFd
        cbd4dSllkul8s68RQ5WxIjfwWYMdfYLiLLqP1lkz4UYpwAW/t63qBx3jRhPgkUxh
        5saJP9Qu5aM1MDMwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMB
        MAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDSQAwRgIhAOIx8885y8tX/Vv94UGx
        hWC/O1Hzi15kOT0WQ/UKUMjMAiEA40uW9P6k+i1cDwgfBBMzgDFQa9GAb4FqM8Wr
        PaUMdqg=
        -----END CERTIFICATE-----
    to:
      kind: Service
      name: bz1829779
      weight: 100
    wildcardPolicy: None
