apiVersion: v1
kind: List
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: hello-staging-insecure
    labels:
      app: hello-staging
      type: staging
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: hello-staging
    host: hello-staging-insecure.staging.apps.amcdermo-2021-01-15-0830.gcp.devcluster.openshift.com
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: hello-staging-edge
    labels:
      app: hello-staging
      type: staging
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: hello-staging
    host: hello-staging-edge.staging.apps.amcdermo-2021-01-15-0830.gcp.devcluster.openshift.com
    
