#!/usr/bin/env bash

set -eu

mkdir -p /tmp/lib/haproxy/router/{certs,cacerts,whitelists}
mkdir -p /tmp/lib/haproxy/{conf/.tmp,run,bin,log}
touch /tmp/lib/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config}

