#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function finalize_results() {
    exec 1>&0
    tar zcf "${jobdir}.tar.gz" "$jobdir"
    echo "Summary: ${jobdir}/summary"
    echo "Results: ${jobdir}.tar.gz"
    echo "sha1sum: $(sha1sum "${jobdir}.tar.gz")"
}

: ${N:=100}

url=${1:?no URL specified}
shift;

token=$(date +%s)
date=$(date +%Y-%m-%d-%H%M%S.%3N)
route=$(echo "$url" | sed -e 's/:/-/g' -e 's/\//-/g' | sed -e 's/-$//')
jobdir="curl-tracer-${date}-N${N}-${route}"

mkdir -p "${jobdir}"

i=0
echo "curl -k -L --trace-time --trace-ascii ${jobdir}/trace-output-$i.trace --output ${jobdir}/curl-output-$i.stdout -w ${i} $(date +%H:%M:%S.%3N) namelookup %{time_namelookup} connect %{time_connect} app_connect %{time_appconnect} pretransfer %{time_pretransfer} starttransfer %{time_starttransfer} status %{http_code} port %{local_port} total %{time_total}" "$@" "$url" > "$jobdir/command"

exec 1<>"${jobdir}/summary"
trap finalize_results EXIT

while [[ $N -eq -1 ]] || [[ $i -lt $N ]];
do
    curl -o /dev/null -k -L -s --trace-time --trace-ascii "${jobdir}/trace-output-$i.trace" --output "${jobdir}/curl-output-$i.stdout" -w "${i} $(date +%H:%M:%S.%3N) namelookup %{time_namelookup} connect %{time_connect} app_connect %{time_appconnect} pretransfer %{time_pretransfer} starttransfer %{time_starttransfer} status %{http_code} port %{local_port} total %{time_total} num_connects %{num_connects}\n" "$@" "$url/?queryid=${i}&token=${token}" || /bin/true
    i=$(( i + 1 ))
done
