apiVersion: v1
kind: List
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: bz1996767-passthrough
    labels:
      app: bz1996767
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: Redirect
  spec:
    port:
      targetPort: 8443
    to:
      kind: Service
      name: bz1996767
