apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: bz1996767
    labels:
      app: bz1996767
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: serving-cert-bz1996767
  spec:
    selector:
      app: bz1996767
    ports:
      - port: 8443
        name: http
        targetPort: 8443
        protocol: TCP
- apiVersion: v1
  kind: Pod
  metadata:
    name: bz1996767
    labels:
      app: bz1996767
  spec:
    containers:
    - image: quay.io/amcdermo/bz1996767-server:master-gab35c7b
      imagepullpolicy: always
      name: bz1996767
      ports:
      - containerPort: 8443
        name: "https"
        protocol: TCP
      volumeMounts:
      - mountPath: /etc/serving-cert
        name: cert
    volumes:
    - name: cert
      secret:
        secretName: serving-cert-bz1996767
