apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: bz1996767
    labels:
      app: bz1996767
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: serving-cert-bz1996767
  spec:
    selector:
      app: bz1996767
    ports:
    - port: 8443
      name: "https"
      targetPort: 8443
    - port: 8080
      name: "http"
      targetPort: 8080
- apiVersion: v1
  kind: Pod
  metadata:
    name: bz1996767
    labels:
      app: bz1996767
  spec:
    containers:
    - image: quay.io/amcdermo/bz1996767-server:master-ge1d14b1
      imagepullpolicy: always
      name: bz1996767
      ports:
      - containerPort: 8443
        name: "https"
      - containerPort: 8080
        name: "http"
      volumeMounts:
      - mountPath: /etc/serving-cert
        name: cert
    volumes:
    - name: cert
      secret:
        secretName: serving-cert-bz1996767
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: bz1996767-passthrough
    labels:
      app: bz1996767
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: Redirect
  spec:
    port:
      targetPort: 8443
    to:
      kind: Service
      name: bz1996767
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: bz1996767-edge
    labels:
      app: bz1996767
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: bz1996767
