apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-app-scale-on-ready-nodes
spec:
  scaleTargetRef:
    name: test-app
  minReplicaCount: 1
  maxReplicaCount: 20
  cooldownPeriod: 1
  pollingInterval: 1
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 3
          policies:
          - type: Percent
            value: 100
            periodSeconds: 1
        scaleUp:
          stabilizationWindowSeconds: 3
          policies:
          - type: Percent
            value: 100
            periodSeconds: 1
  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      namespace: openshift-ingress-operator
      metricName: 'ready-nodes'
      threshold: '1'
      query: 'avg_over_time(ready_nodes{service="nodes-ready-app"}[1m])'
      authModes: "bearer"
    authenticationRef:
      name: keda-trigger-auth-prometheus
