# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

case "$(hostname)" in
    "e20-h29-7525.alias.bos.scalelab.redhat.com")
	PS1="\u@perf_mb\n$ "
	;;
    "e20-h31-7525.alias.bos.scalelab.redhat.com")
	PS1="\u@perf_backend\n$ "
	;;
    "e20-h33-7525.alias.bos.scalelab.redhat.com")
	PS1="\u@perf_haproxy\n$ "
	;;
esac
