apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: hello
    labels:
      app: hello
  spec:
    selector:
      app: hello
    ports:
      - port: 8080
        name: 8080-http
        targetPort: 8080
        protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hello
  spec:
    replicas: 1
    template:
      metadata:
        name: hello
        labels:
          app: hello
      spec:
        containers:
        - image: openshift/hello-openshift
          name: hello
          ports:
            - name: "http"
              containerPort: 8080
      imagePullPolicy: IfNotPresent
    selector:
      matchLabels:
        app: hello
        
