apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-app-scale-on-hello-app
spec:
  scaleTargetRef:
    name: test-app
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 1
  cooldownPeriod:  1            # second
  triggers:
  - type: kubernetes-workload
    metadata:
      podSelector: 'app=hello'
      value: '1'
