apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ic-prometheus-scaledobject
spec:
  scaleTargetRef:
    apiVersion: operator.openshift.io/v1
    kind: IngressController
    name: default
    envSourceContainerName: ingress-operator
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 1
  cooldownPeriod:  1            # seconds
  triggers:
  - type: prometheus
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      namespace: openshift-ingress-operator
      metricName: http_requests_total
      threshold: '1'
      query: sum(rate(http_requests_total{job="test-app"}[1m]))
      authModes: "bearer"
    authenticationRef:
      name: keda-trigger-auth-prometheus
