#!/bin/bash

TOPDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"
config_file=$TOPDIR/haproxy.cfg

haproxy_binary=/usr/sbin/haproxy
haproxy_binary=/home/aim/src/github.com/frobware/haproxy-2.2/haproxy

set -o nounset

pid_file=/tmp/lib/haproxy/run/haproxy.pid
old_pids=$(pidof haproxy)

PATH=/home/aim/src/github.com/frobware/haproxy-2.2:$PATH

reload_status=0
if [ -n "$old_pids" ]; then
    #export LD_PRELOAD=/home/aim/glibc-malloc-trace-utils/libmtrace.so
    haproxy -f $config_file -p $pid_file -x /tmp/lib/haproxy/run/haproxy.sock -sf $old_pids
    #haproxy -f $config_file -p $pid_file -x /tmp/lib/haproxy/run/haproxy.sock -sf $old_pids
    reload_status=$?
else
    haproxy -f $config_file -p $pid_file
    reload_status=$?
fi

[ $reload_status -ne 0 ] && exit $reload_status
